/*
-- Query: SELECT * FROM tutorias.usuarios
LIMIT 0, 1000

-- Date: 2012-08-07 16:03
*/
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (1,'gilberto','gilberto','0','hombre','lord@sep.gob.mx','0','gilberto','0',1,0,0,1,1);
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (2,'victor','victor','0','hombre','victor.aguilar@ciencias.unam.mx','0','victor','0',1,0,0,1,1);
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (3,'toño','toño','0','hombre','antoniohernandez@ciencias.unam.mx','0','toño','0',1,0,0,1,1);
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (4,'hector','hector','0','hombre','hector@gmail.com','0','hector','0',1,0,0,1,1);
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (22,'AlmaQ','Alma','Cuervo','mujer','.','0','12345','0',1,0,0,4,1);
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (23,'Naye','NAYELI','MEJIA BECERRA','mujer','yeli.admonedu@gmail.com','5517006837','231988','.',1,0,0,1,1);
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (26,'FIGAR','Jose Fidel','Garcia Reyes','hombre','figar99@hotmail.com','2224265209','250478_fg','SEB',1,0,0,1,1);
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (30,'Arturo','Arturo','Rodríguez Guerrero','hombre','.','.','12345','.',1,0,0,1,1);
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (33,'Martiux','Martha','Casas','mujer','martiux21@gmail.com','.','soyel5toelement','.',1,0,0,1,1);
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (34,'Virginia','Virginia','Mazón','mujer','.','.','12345','.',1,0,0,4,1);
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (35,'Héctor','Héctor','Monges Morán','hombre','.','.','12345','.',1,0,0,1,1);
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (36,'Jokabed','Jokabed','Zagoya Mellado','mujer','.','.','12345','.',1,0,0,4,1);
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (40,'Sara','Sara','Vogel','mujer','.','.','12345','.',1,0,0,4,1);
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (42,'María Esther','María Esther','Padilla Medina','mujer','.','.','12345','.',1,0,0,4,1);
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (47,'tutoriara','Araceli','Castillo','mujer','araseppe@gmail.com','.','licearatutoria','.',1,0,0,1,1);
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (49,'Adán Rivera','Adán','Rivera Ramos','hombre','adals.guana@hotmail.com','01(55)36014000','chinaproduce','.',1,0,0,1,1);
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (50,'ekutoru','hector','monges morán','hombre','ekutoru@yahoo.com','36014000 ext.23907','iakattakai','.',1,0,0,1,1);
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (51,'Alvarín','Álvaro','de Ávila Aguilar','hombre','2012alavag@gmail.com','4925442952','ALVARINES2','.',1,0,0,1,1);
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (52,'patt_rodriguez','Patricia','Rodríguez Cordero','mujer','patrirod_24@yahoo.com.mx','5529547304','patricia','.',1,0,0,1,1);
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (53,'ALVARIN','ALVARO','DE AVILA AGUILAR','hombre','2012alavag@gmail.com','4925442952','ALVARINES3','.',1,0,0,1,1);
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (54,'Diana','diana','lopez','mujer','dyana3@gmail.com','.','caminando3','.',1,0,0,1,1);
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (55,'Yolito','Laura Beatriz','Meneses Chico','mujer','pejpeni@gmail.com','5525130226','marakatu','.',1,0,0,1,1);
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (56,'alvarin2','Álvaro','de Ávila Aguilar','hombre','2012alavag@gmail.com','4925442952','ALVARINES4','.',1,0,0,1,1);
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (57,'Pablo26','JUAN PABLO','REYES BERNAL','hombre','rpjb26@hotmail.com','5529409418','cucopupes2609','.',1,0,0,1,1);
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (58,'Pilar','Pilar','Herrera','mujer','pilar.multigrado@gmail.com','55-1008-6909','contraseña','.',1,0,0,1,1);
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (59,'Joka','Jokabed','Zagoya Mellado','mujer','jozam_burbuja@yahoo.com.mx','.','lindavenus23','.',1,0,0,1,1);
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (60,'luisge','Luis Gerardo','Cisneros Hernández','hombre','luisge8@yahoo.com.mx','5531904353','amanda','.',1,0,0,1,1);
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (61,'smzamudio','Sandra','Zamudio Hernández','mujer','sandzam@hotmail.com','46221298','europa41','.',1,0,0,1,1);
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (62,'vic','victor','aguilar Gonzaga','hombre','victor.aguilar@yahoo.com.mx','21579919','vic','.',1,0,0,1,1);
INSERT INTO `usuarios` (`idUsuario`,`nick`,`nombre`,`apellidos`,`sexo`,`email`,`telefono`,`contraseña`,`cct`,`idEntidad`,`idMunicipio`,`idLocalidad`,`idNodo`,`idTurno`) VALUES (27182,'esviap','esviap','sistema','mujer','deathstar@la69.sep','0','8182','0',1,0,0,1,1);
